In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)

In [2]:
df = pd.read_csv("profile_killers.csv")

In [3]:
df.head()

,Name,Born,Died,Cause of death,Nicknames,Motive,Conviction,Criminal Penalty,Criminal Status,Victims,Span of Crimes,Country,State(s),Date Apprehended
0,Luis Garavito,"Luis Alfredo Garavito Cubillos(1957-01-25)25 January 1957Génova, Quindío, Colombia","12 October 2023(2023-10-12) (aged 66)Valledupar, Colombia",Unknown,The BeastGoofyConflictBonifacio Morera Lizcano,Unknown,Unknown,Unknown,Unknown,"193+ (221, if 2003 confession is to be believed; 142 convicted)[3][4]",1992–1999,ColombiaEcuadorVenezuela,"Valle del Cauca, Boyacá, Meta, Quindío, Risaralda, Cundinamarca, Nariño, Huila, Caquetá, Antioquia and Caldas,[5][page needed] Chone",22 April 1999
1,Pedro López,"Pedro Alonso López (1948-10-08) 8 October 1948 (age 76)Venadillo, Colombia",Unknown,Unknown,The Monster of the Andes,Unknown,"Vehicle theft, murder, rape",Unknown,Unknown,110–300+,1969 – 1980 (possible resumption since 1998),"Colombia, Ecuador, Peru",Unknown,9 March 1980 (first arrest for serial murders)
2,Javed Iqbal,"Javed Iqbal Mughal1961[1][a]Lahore, Punjab, Pakistan","8 October 2001 (aged 40)[2]Lahore, Punjab, Pakistan",Unknown,Kukri,Unknown,Child sex abuseMurder,Unknown,Unknown,100,1998–1999,Pakistan,Unknown,30 December 1999
3,Mikhail Popkov,"Mikhail Viktorovich Popkov (1964-03-07) 7 March 1964 (age 60)Norilsk, Krasnoyarsk Krai, Russian SFSR, USSR[2]",Unknown,Unknown,The WerewolfThe Angarsk ManiacThe Wednesday Murderer,Hatred of prostitutes Misogyny Sexual sadism,Aggravated murder (x78) Attempted aggravated murder (x2),Unknown,Unknown,83 convictions; 86 confessed[1],1992 – 2010 (confirmed)1992 – 2012 (possible),Russia,Irkutsk OblastPrimorsky Krai,"June 23, 2012"
4,Daniel Camargo Barbosa,"Daniel Camargo Barbosa(1930-01-22)22 January 1930Anolaima, Cundinamarca, Colombia","13 November 1994(1994-11-13) (aged 64)Guayaquil, Ecuador",Unknown,"""The Sadist of El Charquito""""The Monster of the Mangroves""Manuel Bulgarin Solis",Unknown,Unknown,Unknown,Unknown,72–180,1974–1986,"Colombia, Ecuador","Guayas, Pichincha, Tungurahua, El Oro, Los Ríos",3 May 1974; escaped November 1984; re-apprehended 26 February 1986

In [4]:
def exploracion (df):
    df_info = pd.DataFrame()

    df_info["% nulos"] = round(df.isna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["% no_nulos"] = round(df.notna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["tipo_dato"] = df.dtypes
    df_info["num_valores_unicos"] = df.nunique()

    print(f"""El DataFrame tiene {df.shape[0]} filas y {df.shape[1]} columnas.
    Tiene {df.duplicated().sum()} datos duplicados, lo que supone un porcentaje de {round(df.duplicated().sum()/df.shape[0], 2)}% de los datos.

    Hay {len(list(df_info[(df_info["% nulos"] != "0.0%")].index))} columnas con datos nulos, y son: 
    {list(df_info[(df_info["% nulos"] != "0.0%")].index)}

    y sin nulos hay {len(list(df_info[(df_info["% nulos"] == "0.0%")].index))} columnas y son: 
    {list(df_info[(df_info["% nulos"] == "0.0%")].index)}


    A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:""")
    
    display(df_info.head())

    print("Principales estadísticos de las columnas categóricas:")
    categorial_columns = df.select_dtypes(include="O")
    if not categorial_columns.empty:
        display(categorial_columns.describe().T)
    else:
        print("No hay columnas categóricas en el DataFrame.")

    print("Principales estadísticos de las columnas numéricas:")
    numeric_columns = df.select_dtypes(exclude="O")
    if not numeric_columns.empty:
        # Asegurarse de que las columnas numéricas estén en el tipo adecuado
        numeric_columns = numeric_columns.apply(pd.to_numeric, errors='coerce')  # Forzar conversión a numérico
        display(numeric_columns.describe().T)
    else:
        print("No hay columnas numéricas en el DataFrame.")

    return df_info

In [5]:
exploracion(df)

El DataFrame tiene 711 filas y 14 columnas.
    Tiene 0 datos duplicados, lo que supone un porcentaje de 0.0% de los datos.

    Hay 1 columnas con datos nulos, y son:
    ['Date Apprehended']

    y sin nulos hay 13 columnas y son:
    ['Name', 'Born', 'Died', 'Cause of death', 'Nicknames', 'Motive', 'Conviction', 'Criminal Penalty', 'Criminal Status', 'Victims', 'Span of Crimes', 'Country', 'State(s)']


    A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:

               % nulos % no_nulos tipo_dato  num_valores_unicos
Name              0.0%     100.0%    object                 711
Born              0.0%     100.0%    object                 671
Died              0.0%     100.0%    object                 398
Cause of death    0.0%     100.0%    object                   2
Nicknames         0.0%     100.0%    object                 467

Principales estadísticos de las columnas categóricas:

                 count unique            top freq
Name               711    711  Luis Garavito    1
Born               711    671        Unknown   41
Died               711    398        Unknown  314
Cause of death     711      2        Unknown  710
Nicknames          711    467        Unknown  243
Motive             711     46        Unknown  654
Conviction         711    296        Unknown  209
Criminal Penalty   711      1        Unknown  711
Criminal Status    711      1        Unknown  711
Victims            711    357        Unknown   41
Span of Crimes     711    554        Unknown   81
Country            711    126  United States  236
State(s)           711    302        Unknown  248
Date Apprehended   705    525        Unknown  146

Principales estadísticos de las columnas numéricas:
No hay columnas numéricas en el DataFrame.

                 % nulos % no_nulos tipo_dato  num_valores_unicos
Name                0.0%     100.0%    object                 711
Born                0.0%     100.0%    object                 671
Died                0.0%     100.0%    object                 398
Cause of death      0.0%     100.0%    object                   2
Nicknames           0.0%     100.0%    object                 467
Motive              0.0%     100.0%    object                  46
Conviction          0.0%     100.0%    object                 296
Criminal Penalty    0.0%     100.0%    object                   1
Criminal Status     0.0%     100.0%    object                   1
Victims             0.0%     100.0%    object                 357
Span of Crimes      0.0%     100.0%    object                 554
Country             0.0%     100.0%    object                 126
State(s)            0.0%     100.0%    object                 302
Date Apprehended   0.84%     99.16%    object                 525

In [6]:
# Suponiendo que la fecha tiene el formato "Nacido el DD/MM/AAAA"
df['Born'] = df['Born'].str.extract(r'(\d{4})')

In [7]:
df['Died'] = df['Died'].str.extract(r'(\d{4})')

In [8]:
df['Victims'] = df['Victims'].str.extract(r'(\d+)')

In [9]:
df["Country"] = df["Country"].str.split(" ")

In [10]:
df["Country"] = df["Country"].str[0]

In [11]:
df["Country"] = df['Country'].str.rstrip(',')

In [12]:
df["Country"]

0      ColombiaEcuadorVenezuela
1                      Colombia
2                      Pakistan
3                        Russia
4                      Colombia
                 ...
706                      Canada
707                      United
708                      United
709                      Mexico
710                     Unknown
Name: Country, Length: 711, dtype: object

In [13]:
df.head()

,Name,Born,Died,Cause of death,Nicknames,Motive,Conviction,Criminal Penalty,Criminal Status,Victims,Span of Crimes,Country,State(s),Date Apprehended
0,Luis Garavito,1957,2023,Unknown,The BeastGoofyConflictBonifacio Morera Lizcano,Unknown,Unknown,Unknown,Unknown,193,1992–1999,ColombiaEcuadorVenezuela,"Valle del Cauca, Boyacá, Meta, Quindío, Risaralda, Cundinamarca, Nariño, Huila, Caquetá, Antioquia and Caldas,[5][page needed] Chone",22 April 1999
1,Pedro López,1948,NaN,Unknown,The Monster of the Andes,Unknown,"Vehicle theft, murder, rape",Unknown,Unknown,110,1969 – 1980 (possible resumption since 1998),Colombia,Unknown,9 March 1980 (first arrest for serial murders)
2,Javed Iqbal,1961,2001,Unknown,Kukri,Unknown,Child sex abuseMurder,Unknown,Unknown,100,1998–1999,Pakistan,Unknown,30 December 1999
3,Mikhail Popkov,1964,NaN,Unknown,The WerewolfThe Angarsk ManiacThe Wednesday Murderer,Hatred of prostitutes Misogyny Sexual sadism,Aggravated murder (x78) Attempted aggravated murder (x2),Unknown,Unknown,83,1992 – 2010 (confirmed)1992 – 2012 (possible),Russia,Irkutsk OblastPrimorsky Krai,"June 23, 2012"
4,Daniel Camargo Barbosa,1930,1994,Unknown,"""The Sadist of El Charquito""""The Monster of the Mangroves""Manuel Bulgarin Solis",Unknown,Unknown,Unknown,Unknown,72,1974–1986,Colombia,"Guayas, Pichincha, Tungurahua, El Oro, Los Ríos",3 May 1974; escaped November 1984; re-apprehended 26 February 1986

In [14]:
df["Criminal Penalty"].value_counts()

Criminal Penalty
Unknown    711
Name: count, dtype: int64

In [15]:
df["Criminal Status"].value_counts()

Criminal Status
Unknown    711
Name: count, dtype: int64

In [17]:
df["Cause of death"].value_counts()

Cause of death
Unknown                          710
Execution by lethal injection      1
Name: count, dtype: int64

In [20]:
df = df.drop(["Criminal Penalty", "Criminal Status", "Cause of death"], axis=1)

In [21]:
df.head()

,Name,Born,Died,Nicknames,Motive,Conviction,Victims,Span of Crimes,Country,State(s),Date Apprehended
0,Luis Garavito,1957,2023,The BeastGoofyConflictBonifacio Morera Lizcano,Unknown,Unknown,193,1992–1999,ColombiaEcuadorVenezuela,"Valle del Cauca, Boyacá, Meta, Quindío, Risaralda, Cundinamarca, Nariño, Huila, Caquetá, Antioquia and Caldas,[5][page needed] Chone",22 April 1999
1,Pedro López,1948,NaN,The Monster of the Andes,Unknown,"Vehicle theft, murder, rape",110,1969 – 1980 (possible resumption since 1998),Colombia,Unknown,9 March 1980 (first arrest for serial murders)
2,Javed Iqbal,1961,2001,Kukri,Unknown,Child sex abuseMurder,100,1998–1999,Pakistan,Unknown,30 December 1999
3,Mikhail Popkov,1964,NaN,The WerewolfThe Angarsk ManiacThe Wednesday Murderer,Hatred of prostitutes Misogyny Sexual sadism,Aggravated murder (x78) Attempted aggravated murder (x2),83,1992 – 2010 (confirmed)1992 – 2012 (possible),Russia,Irkutsk OblastPrimorsky Krai,"June 23, 2012"
4,Daniel Camargo Barbosa,1930,1994,"""The Sadist of El Charquito""""The Monster of the Mangroves""Manuel Bulgarin Solis",Unknown,Unknown,72,1974–1986,Colombia,"Guayas, Pichincha, Tungurahua, El Oro, Los Ríos",3 May 1974; escaped November 1984; re-apprehended 26 February 1986

In [27]:
df["Died"].isnull().sum()

316

In [24]:
df["Span of Crimes"].value_counts()

Span of Crimes
Unknown                            81
1987–1988                           4
1981–1983                           4
1991–1992                           3
1980–1981                           3
                                   ..
1961–1983                           1
1968–1979                           1
21 January 1990 – 16 March 1995     1
7 June 1990 – 4 March 1992          1
July 7, 1974 – January 8, 1975      1
Name: count, Length: 554, dtype: int64

In [23]:
df["Conviction"].value_counts()

Conviction
Unknown                                                                         209
Murder                                                                          134
First degree murder                                                              13
Capital murder                                                                    8
MurderRape                                                                        6
                                                                               ...
Second degree murder (1982)Six counts of first degree murder (2008)               1
Murder with aggravating circumstances (x36)                                       1
Murder (7 counts)Attempted murder (3 counts)                                      1
First degree murder with special circumstances (6 counts)First degree murder      1
Serial killing                                                                    1
Name: count, Length: 296, dtype: int64

In [22]:
df["Motive"].value_counts()

Motive
Unknown                                                                 654
Financial gain                                                            5
Sexual sadism                                                             4
Life insurance money                                                      3
Sexual sadismPossessionNecrophilia                                        2
Misogyny[1]                                                               2
Robbery                                                                   2
Attention seeking                                                         1
Sexual sadismpedophiliacannibalism                                        1
RageRobberyRapeSadism                                                     1
Sexual compulsion, hatred                                                 1
Sexual sadism[1]PossessionControl                                         1
LustDominationPossession                                                  1
Sexual sadismRobbery                                                      1
Schizophrenia                                                             1
Mental illness                                                            1
Pedophilia                                                                1
Unclear, possibly sexual fetishism and/or sadism                          1
"To get their voices"                                                     1
Inconclusive (likely revenge with grandiosity accompaniment)              1
PossessionControlSexual sadism                                            1
Life insurance                                                            1
Attention due to factitious disorder imposed on another                   1
Child sexual abuseRape[1]                                                 1
Unclear                                                                   1
Sexual sadismPossessionControl[1]                                         1
Blood drinking, sexual pleasure, necrophilia, schizophrenia               1
Hatred of prostitutes  Misogyny  Sexual sadism                            1
Sexual sadismRage[1]                                                      1
Misanthropy, robbery                                                      1
Resentment towards the rich and women                                     1
ControlPossessionNecrophilia                                              1
Rage[1]                                                                   1
Monetary gain                                                             1
Racism[1]                                                                 1
Life insurance moneySearch for "the real romance of life"                 1
paraphiliapossession[1]necrophilia                                        1
Lust murder                                                               1
Sadistic sexual gratification[1]Vengeance against society[2]              1
Desire to incite a race war                                               1
Financial trouble                                                         1
Unknown[5]                                                                1
Sexual sadismMisogyny                                                     1
Unknown, possibly alcoholism                                              1
Profit                                                                    1
Inconclusive; notoriety and misanthropy appear to be primary factors      1
Name: count, dtype: int64

In [16]:
df["State(s)"].value_counts()

State(s)
Unknown                    248
California                  39
New York                    17
Texas                       11
Florida                      8
                          ...
St. Petersburg               1
Wenzhou                      1
Nairobi                      1
Rhine Province, Prussia      1
Sonora                       1
Name: count, Length: 302, dtype: int64